services:
  # Backend Service
  - type: web
    name: mimi-store-backend
    env: python
    buildCommand: |
      cd backend
      find . -type d -name __pycache__ -exec rm -rf {} + || true
      find . -name "*.pyc" -delete || true
      pip install -r requirements.txt
      python manage.py makemigrations --noinput || echo "⚠️ makemigrations failed"
      python manage.py migrate --run-syncdb --noinput || python manage.py migrate --noinput
      python create_superuser.py || echo "⚠️ Superuser already exists"
      python create_coupons.py || echo "⚠️ Coupons already exist"
      python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn ecom_project.wsgi:application

    envVars:
      - key: PYTHONPATH
        value: backend
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ecom-parent-project.onrender.com,0.0.0.0,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: mimi-store-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://ecom-parent-project.onrender.com,http://localhost:3002
      - key: CORS_ALLOW_ALL_ORIGINS # Set to False for production security
        value: False
    
# Database
databases:
  - name: mimi-store-db
    databaseName: mimi_store
    user: mimi_user
