# Generated by Django 5.2.6 on 2026-02-09 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الخصم'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اترك الحقل فارغاً إذا لم يكن هناك خصم', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر بعد الخصم'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الخصم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الأصلي'),
        ),
    ]
