# Generated by Django 5.2.6 on 2026-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('offers', 'صفحة العروض')], default='home', max_length=20, verbose_name='مكان الظهور'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الإعلان من voro'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثانية (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثالثة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرابعة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الخامسة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة السادسة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_7',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة السابعة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_8',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الثامنة (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الرئيسية (voro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, help_text='المنتجات التي تظهر في أسفل صفحة هذا المنتج للزبون', related_name='similar_to', to='products.product', verbose_name='منتجات مشابهة'),
        ),
    ]
