# Generated by Django 5.2.6 on 2026-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_banner_placement_alter_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('offers', 'صفحة العروض'), ('all_products', 'بطاقة «كل المنتجات» في صفحة الأقسام')], default='home', max_length=20, verbose_name='مكان الظهور'),
        ),
    ]
